export const FETCH_SPORTS_REQUEST = 'sports/FETCH_SPORTS_REQUEST';
export const FETCH_SPORTS_SUCCESS = 'sports/FETCH_SPORTS_SUCCESS';
export const FETCH_SPORTS_FAILURE = 'sports/FETCH_SPORTS_FAILURE';
